### ISSUE TITLE
S3 bucket creation failed on s3-eu-west-1.amazonaws.com

### ISSUE THREAD

**Issue by ismetozalp** [appoxy/aws#123]
Hi,
There is bug like this seems to fixed https://github.com/appoxy/aws/pull/40 ,
but when i try to create bucket in eu-west-1 

AWS::S3::DEFAULT_HOST.replace "s3-eu-west-1.amazonaws.com"
AWS::S3::Bucket.create("test", :access => :private)

I got this error

....../aws-s3-0.6.3/lib/aws/s3/error.rb:38:in `raise': The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. (AWS::S3::IllegalLocationConstraintException)
    from /home/ismet/.rvm/gems/ruby-1.9.3-p392/gems/aws-s3-0.6.3/lib/aws/s3/base.rb:72:in`request'
    from /home/ismet/.rvm/gems/ruby-1.9.3-p392/gems/aws-s3-0.6.3/lib/aws/s3/base.rb:88:in `put'
    from /home/ismet/.rvm/gems/ruby-1.9.3-p392/gems/aws-s3-0.6.3/lib/aws/s3/bucket.rb:79:in`create'

**Comment by ssofiagraham-collab** [comment]
Hi
